from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_DIR = BASE_DIR / "data"
SCALABLE_DB_FILE = Path(os.getenv("ATTENDANCE_DB_FILE", str(DATA_DIR / "scalable_attendance.db")))
VECTOR_INDEX_FILE = Path(os.getenv("ATTENDANCE_VECTOR_INDEX_FILE", str(DATA_DIR / "vector_index_v2.npz")))
EMBEDDING_SIZE = 256
FACE_SIZE = (112, 112)
MATCH_THRESHOLD = 0.50
AMBIGUITY_MARGIN = 0.015
ATTENDANCE_COOLDOWN_HOURS = 12
MAX_TOP_K = 5
MAX_FACES_PER_REQUEST = int(os.getenv("ATTENDANCE_MAX_FACES_PER_REQUEST", "10"))
RECOGNITION_CACHE_TTL_SECONDS = int(os.getenv("ATTENDANCE_RECOGNITION_CACHE_TTL_SECONDS", "5"))
DEFAULT_LIST_LIMIT = int(os.getenv("ATTENDANCE_DEFAULT_LIST_LIMIT", "100"))
EMBEDDING_BACKEND = os.getenv("ATTENDANCE_EMBEDDING_BACKEND", "classical")
VECTOR_INDEX_BACKEND = os.getenv("ATTENDANCE_VECTOR_INDEX_BACKEND", "numpy")
ALLOW_BACKEND_FALLBACK = os.getenv("ATTENDANCE_ALLOW_BACKEND_FALLBACK", "true").lower() in {"1", "true", "yes", "on"}
LBPH_CONFIDENCE_THRESHOLD = float(os.getenv("ATTENDANCE_LBPH_CONFIDENCE_THRESHOLD", "78"))
MATCH_CONFIRMATION_FRAMES = int(os.getenv("ATTENDANCE_MATCH_CONFIRMATION_FRAMES", "2"))
MATCH_CONFIRMATION_WINDOW_SECONDS = int(os.getenv("ATTENDANCE_MATCH_CONFIRMATION_WINDOW_SECONDS", "2"))
FAST_ACCEPT_SCORE = float(os.getenv("ATTENDANCE_FAST_ACCEPT_SCORE", "0.82"))
MIN_FACE_WIDTH = int(os.getenv("ATTENDANCE_MIN_FACE_WIDTH", "90"))
MIN_FACE_HEIGHT = int(os.getenv("ATTENDANCE_MIN_FACE_HEIGHT", "90"))
MIN_FACE_BLUR_VARIANCE = float(os.getenv("ATTENDANCE_MIN_FACE_BLUR_VARIANCE", "30"))
MIN_FACE_BRIGHTNESS = float(os.getenv("ATTENDANCE_MIN_FACE_BRIGHTNESS", "35"))
MAX_FACE_BRIGHTNESS = float(os.getenv("ATTENDANCE_MAX_FACE_BRIGHTNESS", "220"))
